/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanchasPresidencialesRouteImport } from './routes/planchas-presidenciales'
import { Route as MiembroMesaRouteImport } from './routes/miembro-mesa'
import { Route as GuiaElectorRouteImport } from './routes/guia-elector'
import { Route as CongresoRouteImport } from './routes/congreso'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatoIdRouteImport } from './routes/candidato.$id'

const PlanchasPresidencialesRoute = PlanchasPresidencialesRouteImport.update({
  id: '/planchas-presidenciales',
  path: '/planchas-presidenciales',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembroMesaRoute = MiembroMesaRouteImport.update({
  id: '/miembro-mesa',
  path: '/miembro-mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaElectorRoute = GuiaElectorRouteImport.update({
  id: '/guia-elector',
  path: '/guia-elector',
  getParentRoute: () => rootRouteImport,
} as any)
const CongresoRoute = CongresoRouteImport.update({
  id: '/congreso',
  path: '/congreso',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoIdRoute = CandidatoIdRouteImport.update({
  id: '/candidato/$id',
  path: '/candidato/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/congreso': typeof CongresoRoute
  '/guia-elector': typeof GuiaElectorRoute
  '/miembro-mesa': typeof MiembroMesaRoute
  '/planchas-presidenciales': typeof PlanchasPresidencialesRoute
  '/candidato/$id': typeof CandidatoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/congreso': typeof CongresoRoute
  '/guia-elector': typeof GuiaElectorRoute
  '/miembro-mesa': typeof MiembroMesaRoute
  '/planchas-presidenciales': typeof PlanchasPresidencialesRoute
  '/candidato/$id': typeof CandidatoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/congreso': typeof CongresoRoute
  '/guia-elector': typeof GuiaElectorRoute
  '/miembro-mesa': typeof MiembroMesaRoute
  '/planchas-presidenciales': typeof PlanchasPresidencialesRoute
  '/candidato/$id': typeof CandidatoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparar'
    | '/congreso'
    | '/guia-elector'
    | '/miembro-mesa'
    | '/planchas-presidenciales'
    | '/candidato/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparar'
    | '/congreso'
    | '/guia-elector'
    | '/miembro-mesa'
    | '/planchas-presidenciales'
    | '/candidato/$id'
  id:
    | '__root__'
    | '/'
    | '/comparar'
    | '/congreso'
    | '/guia-elector'
    | '/miembro-mesa'
    | '/planchas-presidenciales'
    | '/candidato/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompararRoute: typeof CompararRoute
  CongresoRoute: typeof CongresoRoute
  GuiaElectorRoute: typeof GuiaElectorRoute
  MiembroMesaRoute: typeof MiembroMesaRoute
  PlanchasPresidencialesRoute: typeof PlanchasPresidencialesRoute
  CandidatoIdRoute: typeof CandidatoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planchas-presidenciales': {
      id: '/planchas-presidenciales'
      path: '/planchas-presidenciales'
      fullPath: '/planchas-presidenciales'
      preLoaderRoute: typeof PlanchasPresidencialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembro-mesa': {
      id: '/miembro-mesa'
      path: '/miembro-mesa'
      fullPath: '/miembro-mesa'
      preLoaderRoute: typeof MiembroMesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-elector': {
      id: '/guia-elector'
      path: '/guia-elector'
      fullPath: '/guia-elector'
      preLoaderRoute: typeof GuiaElectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congreso': {
      id: '/congreso'
      path: '/congreso'
      fullPath: '/congreso'
      preLoaderRoute: typeof CongresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/$id': {
      id: '/candidato/$id'
      path: '/candidato/$id'
      fullPath: '/candidato/$id'
      preLoaderRoute: typeof CandidatoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompararRoute: CompararRoute,
  CongresoRoute: CongresoRoute,
  GuiaElectorRoute: GuiaElectorRoute,
  MiembroMesaRoute: MiembroMesaRoute,
  PlanchasPresidencialesRoute: PlanchasPresidencialesRoute,
  CandidatoIdRoute: CandidatoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
